# Generated by Django 3.2.3 on 2021-05-24 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=30)),
                ('weight', models.IntegerField(default=1)),
                ('time_to_complete', models.IntegerField(default=1)),
            ],
        ),
    ]
